name: GCP Load Balancer Logging Check and Send Slack Alerts
on:
  workflow_dispatch:  # Allows manual trigger
jobs:
  GCP-Load-Balancer-Logging-Check-and-Send-Slack-Alerts:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SATYA }}  # Webhook URL as secret
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STAGE }}  # Set project ID from secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_STAGE }}
      - name: Setting up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_STAGE }}
      - name: Check Load Balancer Logging Status
        id: check_logging
        run: |
          project_id="${{ secrets.GCP_PROJECT_ID_STAGE }}"
          # Fetch all load balancers in the project
          load_balancers=$(gcloud compute forwarding-rules list --global --format="value(name)")
          logging_disabled=false
          alert_message=""

          # Check logging status for each load balancer
          for lb in $load_balancers; do
            logging_status=$(gcloud compute forwarding-rules describe "$lb" --global --format="value(logConfig.enabled)")
            if [[ "$logging_status" == "False" ]]; then
              logging_disabled=true
              alert_message+="Load Balancer Name: $lb\nLogging Status: DISABLED\n\n"
            else
              echo "Load Balancer Logging is ENABLED for $lb."
            fi
          done

          # Create alert file if any logging is disabled
          if [[ "$logging_disabled" == true ]]; then
            echo -e "$alert_message" > load_balancer_logging_alert.txt
          else
            echo "All load balancers have logging enabled."
          fi
      - name: Send Slack Alert if Any Load Balancer Logging is Disabled
        run: |
          # Check if the load_balancer_logging_alert.txt file exists
          if [ -f load_balancer_logging_alert.txt ]; then
            # If file exists, send the Slack notification
            message=$(cat load_balancer_logging_alert.txt)
            curl -X POST -H 'Content-type: application/json' --data "{
              'text': 'GCP_LOAD_BALANCER_LOGGING_ALERT:\n\n$message'
            }" "${{ env.SLACK_WEBHOOK_URL }}"
          else
            echo "All load balancers have logging enabled. No alert will be sent."
          fi
      - name: Send alert to Slack on job failure
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            'text': 'GCP_LOAD_BALANCER_LOGGING_CHECK_ALERT:\n\nThe workflow to check load balancer logging failed for ${{ env.environment }} environment.'
          }" "${{ env.SLACK_WEBHOOK_URL }}"
